/* Generated by :claw at 2019-09-21T21:57:01.172611Z */

#include <stddef.h>
#include "c.h"


#if !defined(__CLAW_API)
#  if defined(_WIN32)
#    define __CLAW_API __declspec(dllexport)
#  elif defined(__GNUC__)
#    define __CLAW_API __attribute__((visibility("default")))
#  else
#    define __CLAW_API
#  endif
#endif

#if defined(__cplusplus)
extern C {
#endif

#ifdef _WIN32
#  include <windows.h>
static HMODULE ___claw_module;

static int ___claw_init_wrapper() {
  ___claw_module = GetModuleHandle(NULL);
  return ___claw_module != NULL;
}

static void ___claw_close_wrapper(void) {
}
#else
#  include <dlfcn.h>
static void* ___claw_module;

static int ___claw_init_wrapper() {
  ___claw_module = dlopen(NULL, RTLD_NOW | RTLD_GLOBAL);
  return ___claw_module != NULL;
}

static void ___claw_close_wrapper(void) {
}
#endif

static void* claw_get_proc_addr(const char *name) {
  if(___claw_module == NULL) {
    return NULL;
  }

#ifdef _WIN32
  return (void*) GetProcAddress(___claw_module, name);
#else
  return dlsym(___claw_module, name);
#endif
}

#if defined(__cplusplus)
extern "C" {
#endif

typedef char* (*___claw_tst_get_node_name_t)(struct tst_node_t);
typedef void (*___claw_tst_set_node_color_t)(struct tst_node_t*, union tst_color_t);
typedef union tst_color_t (*___claw_tst_get_node_color_t)(struct tst_node_t);
typedef enum tst_node_kind (*___claw_tst_get_node_kind_t)(struct tst_node_t);
typedef void (*___claw_tst_add_child_t)(struct tst_node_t*, struct tst_node_t);
typedef void (*___claw_tst_destroy_node_t)(struct tst_node_t);
typedef struct tst_node_t (*___claw_tst_create_named_node_t)(char[16]);
typedef struct tst_node_t (*___claw_tst_create_colored_node_t)(union tst_color_t);
typedef tst_tree_t* (*___claw_tst_create_tree_t)(struct tst_node_t);

static ___claw_tst_get_node_name_t __v_claw_tst_get_node_name;
static ___claw_tst_set_node_color_t __v_claw_tst_set_node_color;
static ___claw_tst_get_node_color_t __v_claw_tst_get_node_color;
static ___claw_tst_get_node_kind_t __v_claw_tst_get_node_kind;
static ___claw_tst_add_child_t __v_claw_tst_add_child;
static ___claw_tst_destroy_node_t __v_claw_tst_destroy_node;
static ___claw_tst_create_named_node_t __v_claw_tst_create_named_node;
static ___claw_tst_create_colored_node_t __v_claw_tst_create_colored_node;
static ___claw_tst_create_tree_t __v_claw_tst_create_tree;

__CLAW_API int ___claw_libctest_loader_F6D054DFA7C9E57DFE1F11FC030D38CD79A3411A() {
  if(___claw_init_wrapper()) {

__v_claw_tst_get_node_name = (___claw_tst_get_node_name_t) claw_get_proc_addr("tst_get_node_name");
__v_claw_tst_set_node_color = (___claw_tst_set_node_color_t) claw_get_proc_addr("tst_set_node_color");
__v_claw_tst_get_node_color = (___claw_tst_get_node_color_t) claw_get_proc_addr("tst_get_node_color");
__v_claw_tst_get_node_kind = (___claw_tst_get_node_kind_t) claw_get_proc_addr("tst_get_node_kind");
__v_claw_tst_add_child = (___claw_tst_add_child_t) claw_get_proc_addr("tst_add_child");
__v_claw_tst_destroy_node = (___claw_tst_destroy_node_t) claw_get_proc_addr("tst_destroy_node");
__v_claw_tst_create_named_node = (___claw_tst_create_named_node_t) claw_get_proc_addr("tst_create_named_node");
__v_claw_tst_create_colored_node = (___claw_tst_create_colored_node_t) claw_get_proc_addr("tst_create_colored_node");
__v_claw_tst_create_tree = (___claw_tst_create_tree_t) claw_get_proc_addr("tst_create_tree");

    ___claw_close_wrapper();
    return 0;
  }
  return 1;
}


__CLAW_API char* ___claw_tst_get_node_name(struct tst_node_t* arg0) {
  char* result = __v_claw_tst_get_node_name((*arg0));
  return result;
}

__CLAW_API void ___claw_tst_set_node_color(struct tst_node_t* arg0, union tst_color_t* arg1) {
  __v_claw_tst_set_node_color(arg0, (*arg1));
}

__CLAW_API union tst_color_t* ___claw_tst_get_node_color(union tst_color_t* arg0, struct tst_node_t* arg1) {
  union tst_color_t result = __v_claw_tst_get_node_color((*arg1));
 (*arg0) = result;
  return arg0;
}

__CLAW_API enum tst_node_kind ___claw_tst_get_node_kind(struct tst_node_t* arg0) {
  enum tst_node_kind result = __v_claw_tst_get_node_kind((*arg0));
  return result;
}

__CLAW_API void ___claw_tst_add_child(struct tst_node_t* arg0, struct tst_node_t* arg1) {
  __v_claw_tst_add_child(arg0, (*arg1));
}

__CLAW_API void ___claw_tst_destroy_node(struct tst_node_t* arg0) {
  __v_claw_tst_destroy_node((*arg0));
}

__CLAW_API struct tst_node_t* ___claw_tst_create_named_node(struct tst_node_t* arg0, char[16] arg1) {
  struct tst_node_t result = __v_claw_tst_create_named_node(arg1);
 (*arg0) = result;
  return arg0;
}

__CLAW_API struct tst_node_t* ___claw_tst_create_colored_node(struct tst_node_t* arg0, union tst_color_t* arg1) {
  struct tst_node_t result = __v_claw_tst_create_colored_node((*arg1));
 (*arg0) = result;
  return arg0;
}

__CLAW_API tst_tree_t* ___claw_tst_create_tree(struct tst_node_t* arg0) {
  tst_tree_t* result = __v_claw_tst_create_tree((*arg0));
  return result;
}

#if defined(__cplusplus)
}
#endif
